#define LINUX 
#define PVR_BUILD_DIR "omap4430_linux"
#define PVR_BUILD_DATE "2012-11-30"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "omapdrm_pvr"
#define SGXCORE 540
#define SGX540 
#define SUPPORT_SGX540 
#define SUPPORT_SGX 
#define SGX_CORE_REV 120
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 0
#define FLIP_TECHNIQUE_FRAMEBUFFER 
#define DEBUG_LINUX_MMAP_AREAS 
#define DEBUG_LINUX_MEM_AREAS 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define PVRSRV_DISABLE_UM_SYNCOBJ_MAPPINGS 1
#if 0
#define DEBUG 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define DEBUG_LINUX_MEM_AREAS 
#define DEBUG_LINUX_MMAP_AREAS 
#define DEBUG_BRIDGE_KM 
#define DEBUG_TRACE_BRIDGE_KM
#else
#define RELEASE
#endif

#define PVRSRV_USSE_EDM_STATUS_DEBUG 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
//#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SGX_DISABLE_VISTEST_SUPPORT 
#define SYS_USING_INTERRUPTS 
#define SUPPORT_PVRSRV_GET_DC_SYSTEM_BUFFER 
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SGX_DYNAMIC_TIMING_INFO 
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_PLATFORM_PRE_REGISTERED 
#define PVR_LDM_PLATFORM_PRE_REGISTERED_DEV "pvrsrvkm_pvr"
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm_pvr"
#define SUPPORT_LARGE_GENERAL_HEAP 
#define XPROC_WORKAROUND_NUM_SHAREABLES 4095
#define SUPPORT_DRI_DRM 
#define SUPPORT_DRI_DRM_EXTERNAL 
#define PVR_SECURE_DRM_AUTH_EXPORT 
#define PVR_DISPLAY_CONTROLLER_DRM_IOCTL 
#define PVR_DRI_DRM_PLATFORM_DEV 
#define PVR_OMAPLFB_DRM_FB 
